predict/urls.py
from django.urls import path

from . import views

app_name = 'predict'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('ajax_search_male/', views.ajax_search_male, name='search_male'),
    path('ajax_search_female/', views.ajax_search_female, name='search_female'),
    path('<slug:name_slug>/', views.PredictView.as_view(), name='predict'),

]

predictions/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predict.urls'))
]

predict/models.py
from django.db import models
from django.urls import reverse

class Relationship(models.Model):
    male_name = models.CharField(max_length=25)
    female_name = models.CharField(max_length=25)
    slug = models.SlugField(max_length=50, default='s')
    header = models.CharField(max_length=25, null=True)
    percent_in_love = models.PositiveIntegerField(blank=True, null=True)
    percent_in_married = models.PositiveIntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.male_name} -- {self.female_name}'

    def get_absolute_url(self):
        return reverse('predict:predict', args=[self.slug])



class MaleName(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return f'{self.name}'


class FemaleName(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return f'{self.name}'

predict/forms.py
from django import forms

from .models import Relationship

class RelationshipForm(forms.ModelForm):

    class Meta:
        model = Relationship
        fields = ('male_name', 'female_name')

    def __init__(self, *args, **kwargs):
        super(RelationshipForm, self).__init__(*args, **kwargs)
        self.fields['male_name'].widget = forms.TextInput(attrs={
            'id': 'man-search-field',
            'placeholder': 'Man'})
        self.fields['female_name'].widget = forms.TextInput(attrs={
            'id': 'woman-search-field',
            'placeholder': 'Woman'})

predict/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View

from .models import (
    Relationship,
    MaleName,
    FemaleName,
)
from .forms import RelationshipForm


class HomePageView(View):

    def get(self, request):
        form = RelationshipForm()
        return render(request, 'predict/home.html',  {'form': form})

    def post(self, request):
        form = RelationshipForm(request.POST)
        print(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            predict = get_object_or_404(
                Relationship,
                male_name=cd.get('male_name'),
                female_name=cd.get('female_name')
            )
            print(predict.get_absolute_url())
        return redirect(predict.get_absolute_url())


class PredictView(View):

    def get(self, request, name_slug):
        form = RelationshipForm()
        prediction = get_object_or_404(Relationship, slug=name_slug)
        return render(request, 'predict/home.html',  {'prediction': prediction,
                                                      'form': form})


def ajax_search_male(request):
    response_data = {}
    search_request = request.GET.get('search_request')

    result_set = MaleName.objects.filter(name__icontains=search_request)[:5]
    result_set = [str(result) for result in result_set]
    response_data['result_set'] = result_set

    return JsonResponse(response_data)


def ajax_search_female(request):
    response_data = {}
    search_request = request.GET.get('search_request')

    result_set = FemaleName.objects.filter(name__icontains=search_request)[:5]
    result_set = [str(result) for result in result_set]
    response_data['result_set'] = result_set

    return JsonResponse(response_data)

predict/templates/predict/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Page {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'predict/css/predict.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

predict/templates/predict/home.html
{% extends 'predict/base.html' %}
{% load static %}
{% block title %} Home page {% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'predict/css/predict.css' %}">
<h1>Тут вы выбираете имена</h1>
<form action="{% url 'predict:home' %}" method="POST">
    {% csrf_token %}
    <div class="container">


        <div id='man'>
            <div class="search">
                <span>{{ form.male_name }}</span>
            </div>
            <div id=result_man>
            </div>
        </div>

        <div id='woman'>
            <div class="search">
                <span>{{ form.female_name }}</span>
            </div>
            <div id=result_woman>
            </div>
        </div>
        <div id="submit">
            <div class="search">
                <span>
                <input type="submit" class='send_button' value="Send">
                </span>
            </div>
        </div>

    </div>


        {% if prediction %}
        <div class="compatibility">
            <h3>Совместимость имен {{ prediction.female_name }} и {{ prediction.male_name }}</h3>
            <h3>Тип взаимотношений - "{{ prediction.header }}"</h3>
            <br>
            <p class='percentage'>Совместимость в любви - {{ prediction.percent_in_love }}%</p>
            <p class='percentage'>Совместимость в браке - {{ prediction.percent_in_married }}%</p>
            <br>
            <p class='description'>{{ prediction.description|center:10}}</p>
        </div>
        {% else %}
        <div class="compatibility">
            <h2>Выберите имена чтобы узнать совместимость!</h2>
        </div>

        {% endif %}


</form>
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>

<script src="{% static 'predict/js/scripts.js' %}"></script>
{% endblock %}